### PR TITLE
trying to fix issue: DBConnection allow attribute override when using refid #100

### PR DESCRIPTION
**Pull request by bulagump**
https://github.com/jakejustus/pct/issues/100

Issue was introduced with this commit:
https://github.com/jakejustus/pct/commit/b34fcd9d34bcdf3c669e7079e441592dee060ea8#diff-8d33a4c8c605fff72ea2c8726df5d64eR185

### CODE REVIEW

**Comment by jakejustus** [comment]
Hi,

Could you just explain what you want to fix in this PR ?

Gilles

**Comment by bulagump** [comment]
When using refid with a db connection, the default value of SingleUser and ReadyOnly are not saved.  In the example below, the connection would attempt to connect in multi-user mode.  If the database was only in single user mode, the error 'There is no server for database..." occurs.  This can be reproduced with using builds 198 - 200.  There may be better approaches to fix the issue, but the below example worked in prior versions of PCT.

<DBConnection id="db" dbName="mydb" dbDir="data/mydb" singleUser="true"/>

<target name="loaddf">
  <PCTLoadSchema srcFile="mydb.df" dlcHome="${progress.DLC}" cpstream="${cpstream}">
    <DBConnection refid="db" />
  </PCTLoadSchema>
</target>

**Comment by bulagump** [comment]
Example:

``` xml
<DBConnection id="db" dbName="mydb" dbDir="data/mydb" singleUser="true"/>

<target name="loaddf">
  <PCTLoadSchema srcFile="mydb.df" dlcHome="${progress.DLC}" cpstream="${cpstream}">
    <DBConnection refid="db" />
  </PCTLoadSchema>
</target>
```

**Comment by jakejustus** [comment]
Thanks, I'll have a look !

Gilles

**Pull request merged**
