### PR TITLE
Feature/add callback support for pct compile

### PR DESCRIPTION
**Pull request by lievencardoen**
Sorry for the mess with the new Pull Request. Don't know If we can attach the comments from the other Pull Request to this one.

Implemented the code review remarks.

### CODE REVIEW

**Comment by cverbiest** [comment]
@lievencardoen I'm intrigued by this PR . 
What is the use case ?

I've been looking for a way to report compilation errors other than parsing the PCT output.
Could the **afterCompile** be used for that ? does it have access to the compiler errors ?

Could the **beforeCompile** be used to skip compile of a source ?

**Comment by lievencardoen** [comment]
Hi Carl,

Our use case is to get the correct translations from a custom translation application in the xlate database. That has to be done before compiling the source. So in my beforeCompile I get the STRING-XREF for the source and parse it with some custom in-house ABL Code. After that the xlate database is populated with the translation data for that source.

For the question regarding compilation errors, you'll have to ask Gilles I guess. I'm just starting to know the code of PCT.

Could the beforeCompile be used to skip compilation of a source? For now not because I do a call to the Callback class (beforeCompile) in compile.p, but after the call has been done, I'm not doing anything with a return value. So PCT just picks up where it left and continues. I guess you could add an output parameter to the beforeCompile call like SkipCompilation, but that looks like code smell to me ;-) 

Hope that helps a little bit ;-)

@gquerret Don't know if this kind of information can be attached to a pull request. If not, remove it and I'll continue discussing this in a private message.

**Comment by gquerret** [comment]
@lievencardoen and @cverbiest: beforeCallback could return an int (or just a boolean) to tell PCT to skip the file.
We could also include an additional object with the compilation status in afterCompile, could be a nice improvement. Anyway, the COMPILER system handle will still be accessible at this stage.

> @gquerret Don't know if this kind of information can be attached to a pull request. If not, remove it and I'll continue discussing this in a private message.

Keep it there, so that anybody can contribute

**Comment by lievencardoen** [comment]
Ok if I do that in a seperate branch? That way I can finish this part and then make some improvements in a seperate feature branch.

**Comment by gquerret** [comment]
> Ok if I do that in a seperate branch? That way I can finish this part and then make some improvements in a seperate feature branch.

Sure !

**Comment by gquerret** [comment]
I've simplified a bit the test case, and it works well for PCTCompile, but not for PCTCompileExt (messages are not displayed). I'll try to have a quick look during this week, or let you fix that next week.

**Comment by lievencardoen** [comment]
Hi Gilles,

What's the status on this?

I'll do a pull of the last changes and have a look.

Lieven

**Comment by gquerret** [comment]
Wasn't able to have a look at the last issue. Test result is available here: https://ci.rssw.eu/job/PCT/view/change-requests/job/PR-346/lastSuccessfulBuild/artifact/emailable-report-11.7-Win.html#m0

**Comment by lievencardoen** [comment]
The PCTCompileTest.java seems to pass, but the PCTCompileExtTest.java hangs forever...

I'll first try executing the build.xml with Ant.

**Comment by gquerret** [comment]
Just found out why test case wasn't working, see last commit

**Comment by gquerret** [comment]
Tests are now OK: https://ci.rssw.eu/job/PCT/view/change-requests/job/PR-346/
@cverbiest (and others) : would returning a boolean in beforeCompile be enough to skip a file ?  And is the compiler system handle enough in after compile ? Or would you need additional information ?

**Comment by lievencardoen** [comment]
Returning a boolean in beforeCompile looks ok for now, but what if you would like something else to happen in the future? Like instead of skipping the file throwing an error (not being able to compile that source). I tried throwing an ABL Error in the Callback Class, but I think it was just eaten up...

**Comment by cverbiest** [comment]
Any mechanism will do , preferably documented what is available.  Can we do PR on the documentation ?
If the overhead is not to great I prefer some kind of structured parameter but I'm afraid that could negatively impact performance

**Comment by gquerret** [comment]
No PR on the documentation. But you can clone the Git repo of the documentation: git@github.com:Riverside-Software/pct.wiki.git and create new branches that will be merged later.

For the method signatures, I was thinking about:
* METHOD PUBLIC CompileCallbackAction beforeCompile(hSrcProc AS HANDLE, ipInFile AS CHARACTER, ipInDir AS CHARACTER).
Where CompileCallbackAction would be an enum with the following members: NONE, SKIP and STOP.

I would probably just introduce this change in this PR, but we can keep in mind that we may overload afterCompile method with an additional object containing the structured list of errors and warnings. As you said, that may consume resources, and that can be done later with method overloading.

**Comment by lievencardoen** [comment]
Great! Thx for all your help @gquerret !

**Comment by gquerret** [comment]
Thanks for your PR!

**Pull request merged**
