### PR TITLE
Issue#256

### PR DESCRIPTION
**Pull request by wilddoug**
LANGUAGES option not honored when XCODE option used

### CODE REVIEW

**Comment by gquerret** [comment]
Did you mean to keep it open ? Or did you really want to cancel it ?

**Comment by wilddoug** [comment]
Apologies.  Got a little click-happy.  I did mean to keep this open.

**Comment by gquerret** [comment]
Test 58 in PCTCompile already has some tests for the `LANGUAGES` option, would you be able to extend it to make sure that it works correctly with `XCODE` ? And also that it won't be broken with any future change !

**Comment by gquerret** [comment]
For your information, here is the test directory: https://github.com/Riverside-Software/pct/tree/master/tests/PCTCompile/test58
And the Java method: https://github.com/Riverside-Software/pct/blob/master/src/test/com/phenix/pct/PCTCompileTest.java#L932

**Pull request merged**
