### PR TITLE
Feature/add callback support for pct compile

### PR DESCRIPTION
**Pull request by lievencardoen**
I've added an extra parameter **CallbackClass** to PCTCompile and PCTCompileExt. 

It allows you to specify an ABL Class implementing the rssw.pct.ICompileCallback Interface. You can also extend the abstract Class rssw.pct.AbstractCompileCallback.cls.

rssw.pct.ICompileCallback has three methods, initialize, beforeCompile and afterCompile. These methods are all called from within compile.p.

- **initialize** is called from within compile.p::initModule right after the CallbackClass has been dynamically created.
- **beforeCompile** is called from within compile.p::compileXref right before RUN of pctcompile.p.
- **afterCompile** is called from within compile.p::compileXref right after RUN of pctcompile.p.

I've created two tests, one for PCTCompile and one for PCTCompileExt. 

Since I've used PCTLoadData as a basis to implement the Callback Class, I've copied the fact that Callbacks are only supported on 11.3+. However, I didn't test the PCTCompile and PCTCompileExt against an 11.1 or 11.2 for instance. I did try to test against 10.2b but I got a lot of errors that didn't have anything to do with the new logic. In compile.p there is some logic checking the OE Version. I'm not very confident of that logic. So if someone could review that...

Kind regards, Lieven Cardoen

### CODE REVIEW

**Comment by gquerret** [comment]
Very good PR, almost ready to be merged !
* Rebase branch to origin/master (PR for PCTBinaryLoad is included in this PR)
* Parameter name is OK
* A few really minor formatting issues
* AbstractCompileCallback should be abstract
* Verify in tests (test4) that parameters are correctly passed to callback (not just a text file)
* Test in PCTCompileExtTest should have the same name (test76 not test108)

**Comment by lievencardoen** [comment]
Hi Gilles,

I didn't explicetely close the pull request. Don't know how that happened. I did had to rebase my branch because the PR for PCTBinaryLoad was indeed included.

Do I create a new Pull Request?

All of your remarks have been implemented except for

* Verify in tests (test4) that parameters are correctly passed to callback (not just a text file)

You probably mean test76? And how do I test that the parameters were correctly passed to the callback? Can you help me with that? Do I do that in the ABL Callback Class (like IF NOT param = "..." THEN RETURN ERROR...?

**Comment by lievencardoen** [comment]
Or do I write the parameters to the text file? And then check the text file for the correct parameters...

**Comment by gquerret** [comment]
You can reopen the PR. Be also careful when rebasing, as I've had to change the master branch in the main repo (yes, that's ugly, sorry).

**Comment by gquerret** [comment]
> * Verify in tests (test4) that parameters are correctly passed to callback (not just a text file)
> You probably mean test76? And how do I test that the parameters were correctly passed to the callback? Can you help me with that? Do I do that in the ABL Callback Class (like IF NOT param = "..." THEN RETURN ERROR...?

Sorry for the confusion, test4 was for PCTBinaryLoadTest. That's already merged, but if you have time to add this test, that would be perfect.

**Comment by lievencardoen** [comment]
Reopening the PR won't be possible. I had to recreate it in order to get rid of the PCTBinaryLoadTest commits that were in between. Maybe you have a way to reopen it... (GitHub says the feaure/add-callback-support-for-pct-compile branch was force-pushed or recreated).

Still not clear what you mean with adding this test. PCTBinaryLoad does not have a callback, so do you mean adding some extra tests to test76?

**Comment by gquerret** [comment]
Re-reading the code, I have to add some more explanation.
* If possible, add a check in PCTBinaryLoadTest#test4 to verify that parameters from pf file are really taken into account (your example just use integers, so loading with or without paramFile won't change anything if I understood correctly).
* And in test76, verify the value of the parameters (in `hSrcProc AS HANDLE, ipInFile AS CHARACTER, ipInDir AS CHARACTER`)

**Comment by lievencardoen** [comment]
Implemented all remarks from code review but I think I'll will have to do a new Pull Request...

**Pull request closed without merging**
